[package]
name = "AntiVadim"
version = "0.1.3"
description = "A simple web kiosk app"
authors = ["Dmitry Vishin (aka wish-master)"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-global-shortcut = "2.0.0"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tauri-utils = "2.10.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", features = ["NSWindow", "NSApplication"] }

[dev-dependencies]
tempfile = "3"
url = "2"

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
